### ISSUE TITLE
[BUG] `neoforge:waxables` data map parsing error

### ISSUE THREAD

**Issue by EnderTurret** [Kitteh6660/DramaticDoors#107]
Minecraft Version: **1.21.1**
Mod Loader System: **NeoForge 21.1.83**
DramaticDoors Version: **1.21.1-3.2.7**

I'm getting the following error related to Dramatic Doors's waxables data map entries:
```
[29Nov2024 17:23:24.436] [Worker-Main-22/ERROR] [net.neoforged.neoforge.registries.DataMapLoader/]: Could not read data map of type neoforge:waxables for registry ResourceKey[minecraft:root / minecraft:block]
java.lang.IllegalStateException: Map entry 'Right[ResourceKey[minecraft:block / dramaticdoors:short_copper_door]]' : Failed to parse either. First: No key value in MapLike[{"next_oxidation_stage":"dramaticdoors:short_waxed_copper_door"}]; Second: Failed to parse either. First: No key waxed in MapLike[{"next_oxidation_stage":"dramaticdoors:short_waxed_copper_door"}]; Second: Not a string: {"next_oxidation_stage":"dramaticdoors:short_waxed_copper_door"}
	at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar%23128!/:?]
	at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81) ~[datafixerupper-8.0.16.jar%23128!/:?]
	at TRANSFORMER/neoforge@21.1.83/net.neoforged.neoforge.registries.DataMapLoader.readData(DataMapLoader.java:167) ~[neoforge-21.1.83-universal.jar%23170!/:?]
	at TRANSFORMER/neoforge@21.1.83/net.neoforged.neoforge.registries.DataMapLoader.lambda$load$14(DataMapLoader.java:148) ~[neoforge-21.1.83-universal.jar%23170!/:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at TRANSFORMER/neoforge@21.1.83/net.neoforged.neoforge.registries.DataMapLoader.load(DataMapLoader.java:135) ~[neoforge-21.1.83-universal.jar%23170!/:?]
	at TRANSFORMER/neoforge@21.1.83/net.neoforged.neoforge.registries.DataMapLoader.lambda$load$12(DataMapLoader.java:128) ~[neoforge-21.1.83-universal.jar%23170!/:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
```

The `waxables.json` Dramatic Doors supplies looks eerily similar to its `oxidizables.json`, so I'm guessing this is just a copy-paste error — I think all that needs to be done to fix this is to change out `next_oxidation_stage` for `waxed`.

**Comment by Kitteh6660** [comment]
This will be fixed in next version!

**Comment by Kitteh6660** [comment]
Fixed now.
