### ISSUE TITLE
[BUG] Crash with Consistency+ mod. 

### ISSUE THREAD

**Issue by JesusCanelada** [Kitteh6660/DramaticDoors#14]
Minecraft Version: Fabric loader 1.14.13 , Fabric 1.19.2

DramaticDoors Version: DD 1.19.2-1.4.0 (Fabric)

Crashing on loading game
**To Reproduce**
Steps to reproduce the behavior:  Just install dramatic doors with consistency+ mod, and game will crash

If I disable dramatic doors, the game works normally

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'consistency_plus'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.IllegalArgumentException: Block{minecraft:air} has duplicate property: waterlogged
	at net.minecraft.class_2689$class_2690.method_11669(class_2689.java:152)
	at net.minecraft.class_2689$class_2690.method_11667(class_2689.java:127)
	at io.github.consistencyplus.consistency_plus.core.extensions.CPlusFenceGateBlock.method_9515(CPlusFenceGateBlock.java:22)
	at net.minecraft.class_2248.<init>(class_2248.java:185)
	at net.minecraft.class_2383.<init>(class_2383.java:11)
	at net.minecraft.class_2349.<init>(class_2349.java:57)
	at io.github.consistencyplus.consistency_plus.core.extensions.CPlusFenceGateBlock.<init>(CPlusFenceGateBlock.java:15)
	at io.github.consistencyplus.consistency_plus.core.entries.block.RegistryEntryGroup.lambda$blockRegistration$5(RegistryEntryGroup.java:100)
	at dev.architectury.registry.registries.fabric.RegistriesImpl$RegistrarImpl.register(RegistriesImpl.java:211)
	at dev.architectury.registry.registries.DeferredRegister.register(DeferredRegister.java:76)
	at io.github.consistencyplus.consistency_plus.base.ConsistencyPlusMain.init(ConsistencyPlusMain.java:35)
	at io.github.consistencyplus.consistency_plus.ConsistencyPlus.onInitialize(ConsistencyPlus.java:24)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)

**Comment by Kitteh6660** [comment]
Thanks for reporting, I will look into it!

**Comment by Kitteh6660** [comment]
Should be fixed in version 1.4.0 for 1.18.2 (backported fixes), and 1.4.0_1 for 1.19.2 on Fabric.

**Comment by JesusCanelada** [comment]
Great!! Thank you so much for you work. Long live modders ;)
