### ISSUE TITLE
[BUG] Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER

### ISSUE THREAD

**Issue by aking4125** [Kitteh6660/DramaticDoors#77]
Hello,

Upon starting the server with this mod installed, the server crashes with the following spamed in the console:

```
Suppressed: net.minecraftforge.fml.ModLoadingException: Dramatic Doors (dramaticdoors) encountered an error during the common_setup event phase
java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:118) ~[javafmllanguage-1.19.2-43.3.7.jar%231229!/:?] {}
		at net.minecraftforge.fml.ModLoader.lambda$postEventWithWrapInModOrder$35(ModLoader.java:315) ~[fmlcore-1.19.2-43.3.7.jar%231228!/:?] {}
		at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
		at net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:225) ~[fmlcore-1.19.2-43.3.7.jar%231228!/:?] {re:mixin}
		at net.minecraftforge.fml.ModLoader.postEventWithWrapInModOrder(ModLoader.java:313) ~[fmlcore-1.19.2-43.3.7.jar%231228!/:?] {}
		at net.minecraftforge.registries.GameData.postRegisterEvents(GameData.java:341) ~[forge-1.19.2-43.3.7-universal.jar%231232!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:perf.reduce_blockstate_cache_rebuilds.GameDataMixin,pl:mixin:APP:supermartijn642corelib.mixins.json:GameDataMixin,pl:mixin:A}
		at net.minecraftforge.common.ForgeStatesProvider.lambda$new$4(ForgeStatesProvider.java:25) ~[forge-1.19.2-43.3.7-universal.jar%231232!/:?] {re:classloading}
		at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$23(ModLoader.java:207) ~[fmlcore-1.19.2-43.3.7.jar%231228!/:?] {}
		at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
		at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:207) ~[fmlcore-1.19.2-43.3.7.jar%231228!/:?] {}
		at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$14(ModLoader.java:185) ~[fmlcore-1.19.2-43.3.7.jar%231228!/:?] {}
		at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
		at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:185) ~[fmlcore-1.19.2-43.3.7.jar%231228!/:?] {}
		at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[forge-1.19.2-43.3.7-universal.jar%231232!/:?] {re:classloading}
		at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19.2-20220805.130853-srg.jar%231227!/:?] {re:classloading,re:mixin,pl:mixin:A}
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
		at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
		at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.3.7.jar%2367!/:?] {}
		at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {}
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
		at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {}
		at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {}
		at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
		at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
		at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
		at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19.2-43.3.7.jar%2367!/:1.0] {}
		at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2354!/:?] {}
		at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2354!/:?] {}
		at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2354!/:?] {}
		at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?] {}
		at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
		at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {}
		at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
		at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] {}
		at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
		at com.fizzware.dramaticdoors.forge.forge.compat.BlockCarpentryForgeCompat.registerCompat(BlockCarpentryForgeCompat.java:27) ~[DramaticDoors-QuiFabrge-1.19.2-3.1.5.jar%23817!/:?] {re:classloading}
		at com.fizzware.dramaticdoors.forge.forge.DDForgeRegistry.registerBlocksItems(DDForgeRegistry.java:33) ~[DramaticDoors-QuiFabrge-1.19.2-3.1.5.jar%23817!/:?] {re:classloading}
		at com.fizzware.dramaticdoors.forge.forge.__DDForgeRegistry_registerBlocksItems_RegisterEvent.invoke(.dynamic) ~[DramaticDoors-QuiFabrge-1.19.2-3.1.5.jar%23817!/:?] {re:classloading,pl:eventbus:B}
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114) ~[javafmllanguage-1.19.2-43.3.7.jar%231229!/:?] {}
		... 27 more
```
A crash report isn't created as the server technically didn't stop so I have to kill the java process. Instead, below is the .log files.

[debug.log](https://github.com/Kitteh6660/DramaticDoors/files/13819163/debug.log)
[latest.log](https://github.com/Kitteh6660/DramaticDoors/files/13819164/latest.log)

This doesn't affect Single Player or LAN at all. Any ideas?

**Important Information**
Minecraft Version: **1.19.2**
Mod Loader System: **Forge 43.3.7**
DramaticDoors Version: **DramaticDoors-QuiFabrge-1.19.2-3.1.5.jar**

**Comment by Kitteh6660** [comment]
Must be an issue with BlockCarpentry compat. I will look into it!

**Comment by aking4125** [comment]
Deff with Block Carpentry but the crash isn't caused by both. Just Block Carpentry. Sorry it was an odd issue but I think I got it, 

Cross-referencing this issue: https://github.com/PianoManu/BlockCarpentry/issues/81

**Comment by Kitteh6660** [comment]
It worked in 0.3.1.2 but not 0.3.1.4 but yeah, there appeared to be some sort of issues. For now, you could downgrade to 0.3.1.2.

**Comment by PianoManu** [comment]
Yep it was my mod. I'm very sorry for the inconveniences...

**Comment by Kitteh6660** [comment]
I shall close it now.
